FROM python:3.9.12
RUN apt-get update

WORKDIR /app

COPY ./frontend/requirements.txt ./app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r ./app/requirements.txt

CMD ["streamlit", "run", "./frontend/home.py","--server.enableXsrfProtection=false", "--server.enableCORS=false", "--server.port=8501", "--server.address=0.0.0.0"]