version: "3.10.6"
services:
  postgres:
    image: postgres:14
    restart: on-failure
    container_name: ${POSTGRES_CONTAINER}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_SCHEMA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${CONTAINER_PORT}:5432"
    volumes:
      - ./:/eazystats/
      - ./data.dump:/docker-entrypoint-initdb.d/data.dump
      - ./db/:/docker-entrypoint-initdb.d/db/
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-data:/var/lib/postgresql/data
#
#  backend:
#    image: eazystats-backend
#    retart: on-failure
#    container_name: ${BACKEND_CONTAINER}
#    env_file:
#      - .env-backend
#    ports:
#      - "${CONTAINER_PORT}:8000"


#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres
#    environment:
#      - DB_HOST=postgres
#      - DB_PASSWORD=abcd1234
#    volumes:
#      - ./:/code
#    ports:
#      - "5005:80"

volumes:
  postgres-data: